<a href="https://colab.research.google.com/github/KeysOfLife/Skripsi/blob/main/AprioritesHasil.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Latihan Python/datasetaprioriken.xls')
df.head()

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,KEMASAN,QTY,SATUAN,AREA,GROUP BARANG (Import/ Lokal),...,HET,JENIS SEDIAAN,Minggu KE-,Gudang,Pembayaran,Tanggal Pembayaran,Bulan,Pembayaran - Tgl Jatuh Tempo,Umur Piutang,Keterangan
0,2015-01-05,JANUARI,8801/BLT15-00001,BERLIAN FARM,TYLO-UP 100 G,100G,50.0,PCS,TIMUR2,LOKAL,...,73.75,POWDER,Minggu ke-2,BLT,NaN,NaN,NaN,-42069.0,-42009.0,NaN
1,2015-01-06,JANUARI,1151/JKT15-00002,TJF BOGOR,VITAGEN 100 ML,100 ML,100.0,PCS,BARAT,LOKAL,...,NaN,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN
2,2015-01-06,JANUARI,1151/JKT15-00002,TJF BOGOR,COLDIZEP 250 G,250 G,20.0,PCS,BARAT,LOKAL,...,NaN,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN
3,2015-01-06,JANUARI,1152/JKT15-00003,LASMINO,GRANUCIDE 100 G,100 G,20.0,PCS,BARAT,LOKAL,...,NaN,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN
4,2015-01-06,JANUARI,1153/JKT15-00004,PT.JANU PUTRA BAROKAH-SERANG,VITAGEN 100 ML,100 G,200.0,PCS,BARAT,LOKAL,...,NaN,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   TGL  ORDER                     1408 non-null   datetime64[ns]
 1   BULAN                          1408 non-null   object
 2   NO SPB                         1408 non-null   object
 3   NAMA CUSTOMER                  1408 non-null   object
 4   NAMA BARANG                    1407 non-null   object
 5   KEMASAN                        1407 non-null   object
 6   QTY                            1407 non-null   float64
 7   SATUAN                         1404 non-null   object
 8   AREA                           1407 non-null   object
 9   GROUP BARANG (Import/ Lokal)   1407 non-null   object
 10  TOP (HARI)                     1408 non-null   float64
 11  TGL JATUH TEMPO                2070 non-null   object
 12  1.1                            0 non-null      float64
 13  hpp rata-rata                  0 non-null      float64
 14  HET                            1 non-null      float64
 15  JENIS SEDIAAN                  1 non-null      object
 16  Minggu KE-                     1130 non-null   object
 17  Gudang                         1 non-null      object
 18  Pembayaran                     0 non-null      float64
 19  Tanggal Pembayaran             0 non-null      float64
 20  Bulan                          0 non-null      float64
 21  Pembayaran  - Tgl Jatuh Tempo  2070 non-null   float64
 22  Umur Piutang                   2070 non-null   float64
 23  Keterangan                     0 non-null      float64
dtypes: datetime64[ns](1), float64(11), object(12)
memory usage: 439.4+ KB

In [ ]:
data2021 = df.copy()

In [ ]:
data2021['tahun'] = data2021['TGL  ORDER'].dt.year
data2021.head(3)

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,KEMASAN,QTY,SATUAN,AREA,GROUP BARANG (Import/ Lokal),...,JENIS SEDIAAN,Minggu KE-,Gudang,Pembayaran,Tanggal Pembayaran,Bulan,Pembayaran - Tgl Jatuh Tempo,Umur Piutang,Keterangan,tahun
0,2015-01-05,JANUARI,8801/BLT15-00001,BERLIAN FARM,TYLO-UP 100 G,100G,50.0,PCS,TIMUR2,LOKAL,...,POWDER,Minggu ke-2,BLT,NaN,NaN,NaN,-42069.0,-42009.0,NaN,2015.0
1,2015-01-06,JANUARI,1151/JKT15-00002,TJF BOGOR,VITAGEN 100 ML,100 ML,100.0,PCS,BARAT,LOKAL,...,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN,2015.0
2,2015-01-06,JANUARI,1151/JKT15-00002,TJF BOGOR,COLDIZEP 250 G,250 G,20.0,PCS,BARAT,LOKAL,...,NaN,Minggu ke-2,NaN,NaN,NaN,NaN,-42070.0,-42010.0,NaN,2015.0

In [ ]:
data2021 = data2021[data2021['tahun']== 2021]
data2021.head()

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,KEMASAN,QTY,SATUAN,AREA,GROUP BARANG (Import/ Lokal),...,JENIS SEDIAAN,Minggu KE-,Gudang,Pembayaran,Tanggal Pembayaran,Bulan,Pembayaran - Tgl Jatuh Tempo,Umur Piutang,Keterangan,tahun
71,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Mycovet Plus,100 gr,41.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,NaN,-44247.0,-44202.0,NaN,2021.0
72,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Ciprovet,100 gr,55.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,NaN,-44247.0,-44202.0,NaN,2021.0
73,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Super Carnitol.,100 ml,6.0,btl,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,NaN,-44247.0,-44202.0,NaN,2021.0
74,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Polyvit Stress,1 kg,19.0,tin,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,NaN,-44247.0,-44202.0,NaN,2021.0
75,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Megavit Poultry,1 kg,6.0,tin,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,NaN,-44247.0,-44202.0,NaN,2021.0

In [ ]:
data2021['Bulan'] = data2021['TGL  ORDER'].dt.month_name()
data2021.head(3)

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,KEMASAN,QTY,SATUAN,AREA,GROUP BARANG (Import/ Lokal),...,JENIS SEDIAAN,Minggu KE-,Gudang,Pembayaran,Tanggal Pembayaran,Bulan,Pembayaran - Tgl Jatuh Tempo,Umur Piutang,Keterangan,tahun
71,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Mycovet Plus,100 gr,41.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0
72,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Ciprovet,100 gr,55.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0
73,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Super Carnitol.,100 ml,6.0,btl,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0

In [ ]:
data2021.isna().sum()

TGL  ORDER                          0
BULAN                               0
NO SPB                              0
NAMA CUSTOMER                       0
NAMA BARANG                         1
KEMASAN                             1
QTY                                 1
SATUAN                              1
AREA                                0
GROUP BARANG (Import/ Lokal)        0
TOP (HARI)                          2
TGL JATUH TEMPO                     0
1.1                              1088
hpp rata-rata                    1088
HET                              1088
JENIS SEDIAAN                    1088
Minggu KE-                         58
Gudang                           1088
Pembayaran                       1088
Tanggal Pembayaran               1088
Bulan                               0
Pembayaran  - Tgl Jatuh Tempo       0
Umur Piutang                        0
Keterangan                       1088
tahun                               0
dtype: int64

In [ ]:
datatrain = data2021.copy()
dataeda = data2021.copy()

In [ ]:
datatrain.head(3)

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,KEMASAN,QTY,SATUAN,AREA,GROUP BARANG (Import/ Lokal),...,JENIS SEDIAAN,Minggu KE-,Gudang,Pembayaran,Tanggal Pembayaran,Bulan,Pembayaran - Tgl Jatuh Tempo,Umur Piutang,Keterangan,tahun
71,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Mycovet Plus,100 gr,41.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0
72,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Ciprovet,100 gr,55.0,sct,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0
73,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Super Carnitol.,100 ml,6.0,btl,LAMPUNG,LOKAL,...,NaN,Minggu ke-1,NaN,NaN,NaN,January,-44247.0,-44202.0,NaN,2021.0

In [ ]:
datatrain = datatrain.drop(['KEMASAN', 'AREA','GROUP BARANG (Import/ Lokal)',
                           'TOP (HARI)','TGL JATUH TEMPO','hpp rata-rata',
                           'HET','JENIS SEDIAAN','Minggu KE-','Gudang',
                           'Bulan','Pembayaran  - Tgl Jatuh Tempo','Umur Piutang','Keterangan'], axis=1)

In [ ]:
dataclean = datatrain.drop(['NAMA CUSTOMER ','SATUAN',1.1,'Pembayaran ','Tanggal Pembayaran '],axis=1)

In [ ]:
dataclean = dataclean.reset_index()

In [ ]:
dataclean = dataclean.drop(['index'], axis=1)
dataclean.head()

  TGL  ORDER    BULAN            NO SPB      NAMA BARANG   QTY   tahun
0 2021-01-06  JANUARI  2213/LMP21-00009     Mycovet Plus  41.0  2021.0
1 2021-01-06  JANUARI  2213/LMP21-00009         Ciprovet  55.0  2021.0
2 2021-01-06  JANUARI  2213/LMP21-00009  Super Carnitol.   6.0  2021.0
3 2021-01-06  JANUARI  2213/LMP21-00009   Polyvit Stress  19.0  2021.0
4 2021-01-06  JANUARI  2213/LMP21-00009  Megavit Poultry   6.0  2021.0

In [ ]:
dataclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1088 entries, 0 to 1087
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TGL  ORDER   1088 non-null   datetime64[ns]
 1   BULAN        1088 non-null   object
 2   NO SPB       1088 non-null   object
 3   NAMA BARANG  1087 non-null   object
 4   QTY          1087 non-null   float64
 5   tahun        1088 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 51.1+ KB

In [ ]:
dataclean = dataclean.dropna()
dataclean.isna().sum()

TGL  ORDER     0
BULAN          0
NO SPB         0
NAMA BARANG    0
QTY            0
tahun          0
dtype: int64

In [ ]:
dataclean

     TGL  ORDER     BULAN            NO SPB      NAMA BARANG   QTY   tahun
0    2021-01-06   JANUARI  2213/LMP21-00009     Mycovet Plus  41.0  2021.0
1    2021-01-06   JANUARI  2213/LMP21-00009         Ciprovet  55.0  2021.0
2    2021-01-06   JANUARI  2213/LMP21-00009  Super Carnitol.   6.0  2021.0
3    2021-01-06   JANUARI  2213/LMP21-00009   Polyvit Stress  19.0  2021.0
4    2021-01-06   JANUARI  2213/LMP21-00009  Megavit Poultry   6.0  2021.0
...         ...       ...               ...              ...   ...     ...
1083 2021-12-31  DESEMBER  2517/LMP21-04277     Mycovet Plus  11.0  2021.0
1084 2021-12-31  DESEMBER  2517/LMP21-04277         Ciprovet  20.0  2021.0
1085 2021-12-31  DESEMBER  2517/LMP21-04277   Super Carnitol   2.0  2021.0
1086 2021-12-31  DESEMBER  2517/LMP21-04277   Polyvit Stress   5.0  2021.0
1087 2021-12-31  DESEMBER  2517/LMP21-04277         Vetramin   2.0  2021.0

[1087 rows x 6 columns]

In [ ]:
dataclean[['QTY','tahun']] = dataclean[['QTY','tahun']].astype('int')

In [ ]:
dataclean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1087 entries, 0 to 1087
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TGL  ORDER   1087 non-null   datetime64[ns]
 1   BULAN        1087 non-null   object
 2   NO SPB       1087 non-null   object
 3   NAMA BARANG  1087 non-null   object
 4   QTY          1087 non-null   int64
 5   tahun        1087 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 59.4+ KB

In [ ]:
dataclean.head(3)

  TGL  ORDER    BULAN            NO SPB      NAMA BARANG  QTY  tahun
0 2021-01-06  JANUARI  2213/LMP21-00009     Mycovet Plus   41   2021
1 2021-01-06  JANUARI  2213/LMP21-00009         Ciprovet   55   2021
2 2021-01-06  JANUARI  2213/LMP21-00009  Super Carnitol.    6   2021

In [ ]:
dataclean['hari'] = dataclean['TGL  ORDER'].dt.day_name()
dataclean.head()

,TGL ORDER,BULAN,NO SPB,NAMA BARANG,QTY,tahun,hari
0,2021-01-06,JANUARI,2213/LMP21-00009,Mycovet Plus,41,2021,Wednesday
1,2021-01-06,JANUARI,2213/LMP21-00009,Ciprovet,55,2021,Wednesday
2,2021-01-06,JANUARI,2213/LMP21-00009,Super Carnitol.,6,2021,Wednesday
3,2021-01-06,JANUARI,2213/LMP21-00009,Polyvit Stress,19,2021,Wednesday
4,2021-01-06,JANUARI,2213/LMP21-00009,Megavit Poultry,6,2021,Wednesday

In [ ]:
import plotly.express as px

Item_distr = dataclean.groupby(by = "hari").agg({'QTY' : 'mean'}).reset_index()
Item_distr.sort_values(by = 'QTY', inplace = True)

import plotly.express as px
fig = px.bar(Item_distr, y = 'QTY', x = 'hari', text_auto= '.2s',
             title = "rata rata penjualan obat terbanyak dalam satu minggu")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

In [ ]:
dataclean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1087 entries, 0 to 1087
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TGL  ORDER   1087 non-null   datetime64[ns]
 1   BULAN        1087 non-null   object
 2   NO SPB       1087 non-null   object
 3   NAMA BARANG  1087 non-null   object
 4   QTY          1087 non-null   int64
 5   tahun        1087 non-null   int64
 6   hari         1087 non-null   object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 67.9+ KB

In [ ]:
dataclean.head(10)

,TGL ORDER,BULAN,NO SPB,NAMA BARANG,QTY,tahun,hari
0,2021-01-06,JANUARI,2213/LMP21-00009,Mycovet Plus,41,2021,Wednesday
1,2021-01-06,JANUARI,2213/LMP21-00009,Ciprovet,55,2021,Wednesday
2,2021-01-06,JANUARI,2213/LMP21-00009,Super Carnitol.,6,2021,Wednesday
3,2021-01-06,JANUARI,2213/LMP21-00009,Polyvit Stress,19,2021,Wednesday
4,2021-01-06,JANUARI,2213/LMP21-00009,Megavit Poultry,6,2021,Wednesday
6,2021-01-07,JANUARI,2214/LMP21-00010,LE 435,72,2021,Thursday
7,2021-01-08,JANUARI,6941/LMP21-00012,Dinamix L,5,2021,Friday
8,2021-01-08,JANUARI,6941/LMP21-00012,Vetamix Umum,10,2021,Friday
9,2021-01-08,JANUARI,6941/LMP21-00012,Ciprovet,12,2021,Friday
10,2021-01-08,JANUARI,6941/LMP21-00012,Retardoxi 20 LA,84,2021,Friday

In [ ]:
import plotly.express as px

Item_distr = dataclean.groupby(by = "NAMA BARANG").size().reset_index(name='QTY').sort_values(by = 'QTY',ascending=False).head(5)
import plotly.express as px
fig = px.bar(Item_distr, y='QTY', x='NAMA BARANG', text_auto='.2s',
            title="Jumlah Penjualan Obat terbanyak")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

In [ ]:
Item_distr1 = df.groupby(by = "BULAN").size().reset_index(name='QTY').sort_values(by = 'QTY',ascending=False).head(5)
import plotly.express as px
fig = px.bar(Item_distr1, y='QTY', x='BULAN', text_auto='.2s',
            title="top 5 Bulan jumlah transaksi tertinggi pada 2021")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

# **Modelling**

In [ ]:
from sklearn import preprocessing
def label_encoder(data):
    le = preprocessing.LabelEncoder()
    data = le.fit_transform(data)
    return data

In [ ]:
datatrain['No Transaksi Tabular'] = label_encoder(datatrain['NO SPB'])
datatrain.head(15)

,TGL ORDER,BULAN,NO SPB,NAMA CUSTOMER,NAMA BARANG,QTY,SATUAN,1.1,Pembayaran,Tanggal Pembayaran,tahun,No Transaksi Tabular
71,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Mycovet Plus,41.0,sct,NaN,NaN,NaN,2021.0,0
72,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Ciprovet,55.0,sct,NaN,NaN,NaN,2021.0,0
73,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Super Carnitol.,6.0,btl,NaN,NaN,NaN,2021.0,0
74,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Polyvit Stress,19.0,tin,NaN,NaN,NaN,2021.0,0
75,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,Megavit Poultry,6.0,tin,NaN,NaN,NaN,2021.0,0
76,2021-01-06,JANUARI,2213/LMP21-00009,PT. Rama Jaya,NaN,NaN,NaN,NaN,NaN,NaN,2021.0,0
77,2021-01-07,JANUARI,2214/LMP21-00010,Bapak Askar Tabron,LE 435,72.0,sct,NaN,NaN,NaN,2021.0,1
78,2021-01-08,JANUARI,6941/LMP21-00012,Bapak Widodo,Dinamix L,5.0,sak,NaN,NaN,NaN,2021.0,356
79,2021-01-08,JANUARI,6941/LMP21-00012,Bapak Widodo,Vetamix Umum,10.0,dos,NaN,NaN,NaN,2021.0,356
80,2021-01-08,JANUARI,6941/LMP21-00012,Bapak Widodo,Ciprovet,12.0,tin,NaN,NaN,NaN,2021.0,356
81,2021-01-08,JANUARI,6941/LMP21-00012,Bapak Widodo,Retardoxi 20 LA,84.0,btl,NaN,NaN,NaN,2021.0,356
82,2021-01-08,JANUARI,2215/LMP21-00013,PT. SUJA,Vetiodine,10.0,jerg,NaN,NaN,NaN,2021.0,2
83,2021-01-08,JANUARI,2215/LMP21-00013,PT. SUJA,Enroll,7.0,btl,NaN,NaN,NaN,2021.0,2
84,2021-01-08,JANUARI,2216/LMP21-00014,PT. SUJA,Vetiodine,20.0,jerg,NaN,NaN,NaN,2021.0,3
85,2021-01-08,JANUARI,2216/LMP21-00014,PT. SUJA,Vetramin,15.0,btl,NaN,NaN,NaN,2021.0,3

In [ ]:
Basket = (datatrain[datatrain['tahun']==2021]
          .groupby(['NO SPB', 'NAMA BARANG'])['QTY']
          .sum().unstack().reset_index().fillna(0)
          .set_index('NO SPB'))

Basket.head()

NAMA BARANG,Alben 10,Amox 50,Amox-50,Amox-50,Ampivet-24,Antistress Custom (LC2),Antistress Custom 2 (LC2),Antistress custom 2,Aximol-800,Aximol-800,...,Vetamix umum,Vetamycine,Vetcox,Vethrop,Vethrop-24,Vethropp-24,Vetiodine,Vetramin,Vitagen,Zyrotox
NO SPB,,,,,,,,,,,,,,,,,,,,,
2213/LMP21-00009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2214/LMP21-00010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2215/LMP21-00013,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0
2216/LMP21-00014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,15.0,0.0,0.0
2217/LMP21-00073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
def sum_to_boolean(x):
    if x<=0:
        return 0
    else:
        return 1

Basket_Final = Basket.applymap(sum_to_boolean)

In [ ]:
Basket_Final.head()

NAMA BARANG,Alben 10,Amox 50,Amox-50,Amox-50,Ampivet-24,Antistress Custom (LC2),Antistress Custom 2 (LC2),Antistress custom 2,Aximol-800,Aximol-800,...,Vetamix umum,Vetamycine,Vetcox,Vethrop,Vethrop-24,Vethropp-24,Vetiodine,Vetramin,Vitagen,Zyrotox
NO SPB,,,,,,,,,,,,,,,,,,,,,
2213/LMP21-00009,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2214/LMP21-00010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2215/LMP21-00013,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2216/LMP21-00014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
2217/LMP21-00073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
Frequent_itemsets = apriori(Basket_Final, min_support = 0.04, use_colnames = True)
Frequent_itemsets['length'] = Frequent_itemsets['itemsets'].apply(lambda x: len(x))
Frequent_itemsets.tail()

     support                                           itemsets  length
24  0.043243          (Megavit Poultry, Mycovet Plus, Ciprovet)       3
25  0.050450        (Megavit Poultry, Polyvit Stress, Ciprovet)       3
26  0.041441           (Mycovet Plus, Polyvit Stress, Ciprovet)       3
27  0.046847    (Megavit Poultry, Mycovet Plus, Polyvit Stress)       3
28  0.048649  (Megavit Poultry, Super Carnitol, Polyvit Stress)       3

In [ ]:
Asso_Rules = association_rules(Frequent_itemsets, metric = "lift", min_threshold = 1)
Asso_Rules.sort_values('lift',ascending = False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
26,(Mycovet Plus),"(Megavit Poultry, Ciprovet)",0.066667,0.054054,0.043243,0.648649,12.000000,0.039640,2.692308
23,"(Megavit Poultry, Ciprovet)",(Mycovet Plus),0.054054,0.066667,0.043243,0.800000,12.000000,0.039640,4.666667
43,(Megavit Poultry),"(Mycovet Plus, Polyvit Stress)",0.079279,0.050450,0.046847,0.590909,11.712662,0.042847,2.321121
42,"(Mycovet Plus, Polyvit Stress)",(Megavit Poultry),0.050450,0.079279,0.046847,0.928571,11.712662,0.042847,12.890090
24,"(Mycovet Plus, Ciprovet)",(Megavit Poultry),0.046847,0.079279,0.043243,0.923077,11.643357,0.039529,11.969369

In [ ]:
Asso_Rules = association_rules(Frequent_itemsets, metric = "lift", min_threshold = 1)
Asso_Rules.sort_values(['lift'],ascending = [False])

In [ ]:
Asso_RulesFiltered = Asso_Rules[(Asso_Rules['lift'] >= 11)&(Asso_Rules ['confidence'] >= 0.6)].sort_values(['lift'],ascending = [False])
Asso_RulesFiltered

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
23,"(Megavit Poultry, Ciprovet)",(Mycovet Plus),0.054054,0.066667,0.043243,0.800000,12.000000,0.039640,4.666667
26,(Mycovet Plus),"(Megavit Poultry, Ciprovet)",0.066667,0.054054,0.043243,0.648649,12.000000,0.039640,2.692308
42,"(Mycovet Plus, Polyvit Stress)",(Megavit Poultry),0.050450,0.079279,0.046847,0.928571,11.712662,0.042847,12.890090
24,"(Mycovet Plus, Ciprovet)",(Megavit Poultry),0.046847,0.079279,0.043243,0.923077,11.643357,0.039529,11.969369
30,"(Polyvit Stress, Ciprovet)",(Megavit Poultry),0.055856,0.079279,0.050450,0.903226,11.392962,0.046022,9.514114
31,(Megavit Poultry),"(Polyvit Stress, Ciprovet)",0.079279,0.055856,0.050450,0.636364,11.392962,0.046022,2.596396
36,"(Polyvit Stress, Ciprovet)",(Mycovet Plus),0.055856,0.066667,0.041441,0.741935,11.129032,0.037718,3.616667
37,(Mycovet Plus),"(Polyvit Stress, Ciprovet)",0.066667,0.055856,0.041441,0.621622,11.129032,0.037718,2.495238

In [ ]:
Asso_RulesFiltered = Asso_Rules[(Asso_Rules ['confidence'] >= 0.6)].sort_values(['lift'],ascending = [False])
Asso_RulesFiltered.sort_values(['confidence'],ascending = [False])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
29,"(Megavit Poultry, Ciprovet)",(Polyvit Stress),0.054054,0.115315,0.050450,0.933333,8.093750,0.044217,13.270270
42,"(Mycovet Plus, Polyvit Stress)",(Megavit Poultry),0.050450,0.079279,0.046847,0.928571,11.712662,0.042847,12.890090
24,"(Mycovet Plus, Ciprovet)",(Megavit Poultry),0.046847,0.079279,0.043243,0.923077,11.643357,0.039529,11.969369
30,"(Polyvit Stress, Ciprovet)",(Megavit Poultry),0.055856,0.079279,0.050450,0.903226,11.392962,0.046022,9.514114
35,"(Mycovet Plus, Ciprovet)",(Polyvit Stress),0.046847,0.115315,0.041441,0.884615,7.671274,0.036039,7.667267
40,"(Megavit Poultry, Mycovet Plus)",(Polyvit Stress),0.054054,0.115315,0.046847,0.866667,7.515625,0.040614,6.635135
34,"(Mycovet Plus, Polyvit Stress)",(Ciprovet),0.050450,0.086486,0.041441,0.821429,9.497768,0.037078,5.115676
12,(Megavit Poultry),(Polyvit Stress),0.079279,0.115315,0.064865,0.818182,7.095170,0.055723,4.865766
46,"(Megavit Poultry, Super Carnitol)",(Polyvit Stress),0.059459,0.115315,0.048649,0.818182,7.095170,0.041792,4.865766
11,(Mycovet Plus),(Megavit Poultry),0.066667,0.079279,0.054054,0.810811,10.227273,0.048769,4.866667
22,"(Megavit Poultry, Mycovet Plus)",(Ciprovet),0.054054,0.086486,0.043243,0.800000,9.250000,0.038568,4.567568
23,"(Megavit Poultry, Ciprovet)",(Mycovet Plus),0.054054,0.066667,0.043243,0.800000,12.000000,0.039640,4.666667
28,"(Megavit Poultry, Polyvit Stress)",(Ciprovet),0.064865,0.086486,0.050450,0.777778,8.993056,0.044841,4.110811
16,(Mycovet Plus),(Polyvit Stress),0.066667,0.115315,0.050450,0.756757,6.562500,0.042763,3.637037
14,(Megavit Poultry),(Super Carnitol),0.079279,0.135135,0.059459,0.750000,5.550000,0.048746,3.459459
47,"(Megavit Poultry, Polyvit Stress)",(Super Carnitol),0.064865,0.135135,0.048649,0.750000,5.550000,0.039883,3.459459
36,"(Polyvit Stress, Ciprovet)",(Mycovet Plus),0.055856,0.066667,0.041441,0.741935,11.129032,0.037718,3.616667
41,"(Megavit Poultry, Polyvit Stress)",(Mycovet Plus),0.064865,0.066667,0.046847,0.722222,10.833333,0.042523,3.360000
48,"(Super Carnitol, Polyvit Stress)",(Megavit Poultry),0.068468,0.079279,0.048649,0.710526,8.962321,0.043221,3.180672
2,(Mycovet Plus),(Ciprovet),0.066667,0.086486,0.046847,0.702703,8.125000,0.041081,3.072727
44,(Mycovet Plus),"(Megavit Poultry, Polyvit Stress)",0.066667,0.064865,0.046847,0.702703,10.833333,0.042523,3.145455
0,(Megavit Poultry),(Ciprovet),0.079279,0.086486,0.054054,0.681818,7.883523,0.047197,2.871042
10,(Megavit Poultry),(Mycovet Plus),0.079279,0.066667,0.054054,0.681818,10.227273,0.048769,2.933333
18,(Mycovet Plus),(Super Carnitol),0.066667,0.135135,0.045045,0.675676,5.000000,0.036036,2.666667
26,(Mycovet Plus),"(Megavit Poultry, Ciprovet)",0.066667,0.054054,0.043243,0.648649,12.000000,0.039640,2.692308
5,(Ciprovet),(Polyvit Stress),0.086486,0.115315,0.055856,0.645833,5.600586,0.045883,2.497933
31,(Megavit Poultry),"(Polyvit Stress, Ciprovet)",0.079279,0.055856,0.050450,0.636364,11.392962,0.046022,2.596396
1,(Ciprovet),(Megavit Poultry),0.086486,0.079279,0.054054,0.625000,7.883523,0.047197,2.455255
37,(Mycovet Plus),"(Polyvit Stress, Ciprovet)",0.066667,0.055856,0.041441,0.621622,11.129032,0.037718,2.495238
49,(Megavit Poultry),"(Super Carnitol, Polyvit Stress)",0.079279,0.068468,0.048649,0.613636,8.962321,0.043221,2.411023